### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by blootsvoets** [NLeSC/estep-checklist#12]
Perhaps we can provide a template for the README and NOTICES? For example with

- Standard headers (dependencies, installation, how to run, (code) example, (docker build steps?), documentation, contributing)
- tag placement (travis, codacy)
- link to NLeSC
- license
- link to code of conduct and or contributor guidelines/coding style

**Comment by mkuzak** [comment]
Agree, but this is implementation. Maybe we'll make a simple generator with basics, like yeoman :)

**Comment by jspaaks** [comment]
Or maybe we could use a template project for each of the 5 or so languages we use at NLeSC? People could then fork off of that.

**Comment by mkuzak** [comment]
Ok, now all defaults leave in nlesc/exemplum.
