### ISSUE TITLE
suggested JavaScript style

### ISSUE THREAD

**Issue by jspaaks** [NLeSC/estep-checklist#18]
I have a suggestion for a JavaScript style: Nicholas Zakas has a style guide in his book that we can adopt without changes AFAIC.

**Comment by mkuzak** [comment]
Does it have a linter support?

**Comment by jspaaks** [comment]
I'm guessing [yes](http://eslint.org/)

**Comment by larsmans** [comment]
Is (a summary of it) available online?

**Comment by mkuzak** [comment]
I understand that both the book and eslint are written by the Nicholas Zakas. The question is: is there .eslintrc file adhering to the style he presents in his book? I'd rather not have to write it myself, taking into account the amount of options. As far as I know by default all eslint options are turned off.
There are some configuration files on [Walmartlabs page](https://github.com/walmartlabs/eslint-config-defaults#full-configurations), even my favorite (airbnb). Is the `recommended` the one in line with what is in the book?

**Comment by mkuzak** [comment]
I suggest moving this discussion to [exemplum repository](https://github.com/nlesc/exemplum) since this is the place where the style guides will live.

**Comment by jspaaks** [comment]
OK, cool. Let me just close this then.
