### ISSUE TITLE
links to how in NLeSC/software-development-guide

### ISSUE THREAD

**Issue by arnikz** [NLeSC/estep-checklist#19]

**Comment by mkuzak** [comment]
This is already in big part present in knowledge base, we should limit the replication across out sites. I suggest linking to kb if there is relevant information.
Testing tooling is highly language dependent. I'd love if people added to knowledge base this information per language.

**Comment by nielsdrost** [comment]
I actually vote the checklist will be part of the knowledge base in the end.

**Comment by mkuzak** [comment]
Yes, agree.

**Comment by arnikz** [comment]
Good point(s).

**Comment by elboyran** [comment]
Do we have a pointer to the KB in the checklist?, e.g. 
[KB testing link](https://github.com/NLeSC/kb/wiki/Testing)

**Comment by mkuzak** [comment]
No.

**Comment by mkuzak** [comment]
I think this is agreed, every point should point to relevant entry in what used to be kb and is now NLeSC/software-development-guide

**Comment by nielsdrost** [comment]
A combination of the content of this checklist repo and the kb wiki pages on software development now form the software development chapter of the NLeSC Guide: https://nlesc.gitbooks.io/guide/content/software/code_quality.html
