### ISSUE TITLE
Link to emergency revert for accidentally uploaded confidential data

### ISSUE THREAD

**Issue by egpbos** [NLeSC/estep-checklist#20]
> In case the code uses data, that cannot be open, an engineer should try to keep sensitive parts outside of the main codebase.

It sometimes happens that sensitive data is accidentally uploaded. It would be nice if the checklist has an emergency *get that stuff out of my history* guide (or link to separate guide, e.g. this one https://help.github.com/articles/remove-sensitive-data/).

**Comment by mkuzak** [comment]
Agreed, this is important to have, but should go to documentation.

**Comment by mkuzak** [comment]
Actual solution should not be in the checklist, but we should add a note how to prevent (adding things to .gitignore).

**Comment by mkuzak** [comment]
migrated to https://github.com/NLeSC/guide/issues/7
