### ISSUE TITLE
Link to pitch presentations

### ISSUE THREAD

**Issue by arnikz** [NLeSC/estep-checklist#22]
Could you please add a link to these? Sorry, I can't remember anymore, too bad, I known, pitches should be up-to-date:)

**Comment by mkuzak** [comment]
@arnikz , what do you suggest with this issue? There is already pitch presentation included, or you think we need to link from documentation to pitch presentations? Can you make it more explicit?

**Comment by arnikz** [comment]
Indeed, we could add a link from doc to slides. What is the current place (URL) for pitch presentations?

**Comment by mkuzak** [comment]
I agree it's useful, but think it's and implementation detail, not really part of checklist. But we should remember about it when documenting what we need from documentation.

**Comment by arnikz** [comment]
Sorry for repeating but haven't got an answer on this: what is the current place (URL) for pitch presentations? Thanks.

**Comment by mkuzak** [comment]
I don't know but I think you have better chance of getting an answer to this question, when asking it on slack or office-IT or @nielsdrost than asking it in issue in checklist repository.

**Comment by nielsdrost** [comment]
He @arnikz ,

Pitch presentation at the moment live on the "nlesc  sharepoint. This does not really have a url, as it is not a public location.

However, this will most probably change in the near future :-) Where exactly it will end up is still t.b.d

Niels

**Comment by mkuzak** [comment]
We could require for pitch slides to be in the repository. Or at leas on project github.io pages. That would actually make more sense, since the pitch would probably be about project, not single tool.

**Comment by mkuzak** [comment]
Not a checklist issue, closing it.
