### ISSUE TITLE
README.rst acceptable?

### ISSUE THREAD

**Issue by larsmans** [NLeSC/estep-checklist#26]
We now require a README in Markdown format, but [one of my projects](https://github.com/NLeSC/xtas) has a reStructuredText (.rst) one, because all of my documentation has to be in that format for [Sphinx](http://www.sphinx-doc.org/en/stable/rest.html) and for that same reason rst is common in the Python world. GitHub renders rst as well as md. Can we change the requirement to Markdown *or* RST?

**Comment by mkuzak** [comment]
Good point. Either that, or add in the comment, unless other README format is already in used/required by the project.

**Comment by larsmans** [comment]
Btw., I think GitHub does require the `CONTRIBUTING` doc to be Markdown.

**Comment by mkuzak** [comment]
Just tested it and reStructuredText works fine too, it's also rendered properly by github.

**Comment by nielsdrost** [comment]
There are always exceptions to every rule. I don't think we need to change every rule to include every exception. Perhaps it would be good to list some of the common exceptions in the (verbose) documentation?

**Comment by mkuzak** [comment]
+1 for adding this as corner case in `verbose`

**Comment by mkuzak** [comment]
I think we all agree on what to do about it.
@larsmans looks like you solved int already [here]
(https://github.com/larsmans/estep-checklist/commit/be3a096cad7eea6882364c7868ace9abcbca78c1)
can you make a pull request?

**Comment by larsmans** [comment]
I thought I already had, but I really did now.
