### ISSUE TITLE
add CITATION file

### ISSUE THREAD

**Issue by mkuzak** [NLeSC/estep-checklist#30]
plain text file with explanation how to cite the software,
should include DOI associated with latest release

more aobut CITATION file here:
http://www.software.ac.uk/blog/2013-09-02-encouraging-citation-software-introducing-citation-files

**Comment by jvdzwaan** [comment]
I would overlook such a file. Why not just put it in the README?

**Comment by mkuzak** [comment]
I think file is a nice separation, but we can mention it in documentation.

**Comment by jvdzwaan** [comment]
Could we somehow automate this?

**Comment by blootsvoets** [comment]
Does this duplicate some of the NOTICE file?

**Comment by blootsvoets** [comment]
Ah from the blogs I get that one of the main advantages of a separate file is to put a bibtex entry in there as well, which for example Depsy could parse. The advantage of a NOTICE file is that it's redistributed whenever the source code is, but honestly, probably a bundled software would not get cited anyway.

**Comment by sverhoeven** [comment]
Using Zenodo DOI is I think at this moment the way to citate software.

**Comment by mkuzak** [comment]
DOI is the technology NOTICE is the documentation
