### ISSUE TITLE
rename repository

### ISSUE THREAD

**Issue by mkuzak** [NLeSC/estep-checklist#31]
I think we should rename the repository. It is not eStep checklist any more.
Some ideas are:

- NLeSC software checklist
- research software checklist
- NLeSC software practices
- NLeSC software guide
- NLeSC software guidelines

any ideas?

**Comment by nielsdrost** [comment]
I think it should go into the knowledge base

**Comment by mkuzak** [comment]
I agree that all the documentation for it should go to knowledge base, but would like to keep checklist as repository, maybe add github page to it.

**Comment by mkuzak** [comment]
I'd call it just 'software checklist'

**Comment by mkuzak** [comment]
This repository gets merged into the https://github.com/NLeSC/guide
