### ISSUE TITLE
What should be included in CONTRIBUTING.md

### ISSUE THREAD

**Issue by mkuzak** [NLeSC/estep-checklist#37]
More information on what should contribution guidelines include.
We need more examples and NLeSC templates.

**Comment by sverhoeven** [comment]
Example by me at https://github.com/3D-e-Chem/3D-e-Chem-VM/blob/master/CONTRIBUTING.md

**Comment by mkuzak** [comment]
Migrated to https://github.com/NLeSC/guide/issues/13
